### ISSUE TITLE
New coverage path for coverage data with Xcode 10

### ISSUE THREAD

**Issue by aaroncrespo** [nakiostudio/xcov#135]
Looks like the output path of Xcode coverage tool changed.
Xcode9  : `DerivedData/{build}/Logs/Test/{testpass}.xcovreport` 
Xcode10 : `DerivedData/{build}/Logs/Test/{testpass}.xcresult/1_Test/action.xcovreport`

**Comment by msebgf** [comment]
Is there any workaround to generate the report?

**Comment by aaroncrespo** [comment]
something quick and dirty like #136 might work

**Comment by nakiostudio** [comment]
Fixed thanks to @aaroncrespo.

**Comment by deanWombourne** [comment]
I'm confused, sorry :) I've got this issue, but the latest xcov gem (version 1.3.1) but still can't get it to run?

**Comment by CharlesVu** [comment]
@deanWombourne The latest version of Xcov is 1.5.0

**Comment by deanWombourne** [comment]
How embarrassing, not sure why my `bundle update` wasn't, suspect maybe underlying ruby version maybe? Or maybe just I did something wrong, which is reasonably likely. Obviously, this now works for me :)
